### ISSUE TITLE
Metric input for SMACdown ensemble

### ISSUE THREAD

**Issue by alexschwarm** [whizzml/examples#14]
When running the SMACdown ensemble (https://github.com/whizzml/examples/blob/master/smacdown-ensemble/script.whizzml), there is an option to specify the "metric".  The description text for this input states "Evaluation metric that we want to optimize. It must be a number".  The default value is "average_phi".  It seems if I enter "average_recall" this runs.  It seems that the metric is used here:
33          phi (lambda (ev)
34                (let (metric-value (ev ["result" "model" metric] false))
Should the input text for "metric" be updated to be "Choose from average_recall, average_phi, accuracy, average_precision, or average_f_measure"?

**Comment by jaor** [comment]
@alexschwarm yes, you're right.  i've submitted PR #15 to add the list of available metrics.  actually, we have in the works an improvement to the interface that will allow specification of an enumeration as the type of a script input, and when that's released we'll be able to be even more precise in what we accept here (e.g., the UI will offer a drop-down of allowed values instead of free text).  thanks!
